---
- name: Bind mount /home/mydata to /mnt/mydata
  hosts: all
  tasks:
    - name: Create source and target directories
      ansible.builtin.shell: |
        sudo mkdir -p /home/mydata /mnt/mydata
        sudo chmod 755 /home/mydata /mnt/mydata

    - name: Bind mount /home/mydata to /mnt/mydata
      ansible.builtin.shell: |
        sudo mount --bind /home/mydata /mnt/mydata
     
