---
- name: Gather Ansible Facts
  hosts: all
  gather_facts: true

  tasks:
    - name: Gather Ansible Facts about Installed Packages
      ansible.builtin.package_facts:
          manager: auto

    - name: Gather Additional Facts
      ansible.builtin.setup:
        filter:
          - 'ansible_distribution'
          - 'ansible_machine_id'
          - 'ansible_*_mb'
         
    - name: Install httpd
      ansible.builtin.dnf:
         name: httpd
         state: present

    - name: Start and Enable httpd
      ansible.builtin.service:
         name: httpd
         state: started
         enabled: yes

     
