---
- name: Gather Ansible Facts
  hosts: all
  gather_facts: true

  tasks:
    - name: Gather Ansible Facts about Installed Packages
      ansible.builtin.package_facts:
          manager: auto

    - name: task2
      ansible.builtin.setup:
      filter:
         - 'ansible_distribution'
         - 'ansible_machine_id'
         - 'ansible_*_mb'
         
    - name: task3
      ansible.builtin.dnf:
         name: httpd
         state: present

    - name: task4
      ansible.builtin.service:
         name: httpd
         state: started
         enabled: yes
     
