---
- hosts: all
  tasks:
    - name: task1
      command: "awk -F: '/^awx/{print $2}' /etc/subuid"
      register: awx_uid
    - name: task2
      command: "awk -F: '/^awx/{print $2}' /etc/subgid"
      register: awx_gid
    - ansible.builtin.user:
         name: awx-user
         uid: "{{ awx_uid.stdout }}"
         gid: "{{ awx_gid.stdout }}"
         state: present
~                       
