---
- hosts: all,localhost
  tasks:
     - name: Add host to group 'just_created' with variable foo=42
       ansible.builtin.add_host:
         name: '192.168.122.132'
         groups: just_created
         foo: 42
