---
- name: Update system with security patches only
  hosts: "{{group}}"
  become: true
  tasks:
    - name: Update all packages with security updates
      yum:
        name: "*"
        state: latest
        security: yes
      register: patch_result
    - name: Restart the server
      reboot:
        msg: "Rebooting the server after security patching"
        reboot_timeout: 300
      when: patch_result is changed
    - name: wait for the server  to become available
      wait_for_connection:
        timeout: 300
      when: patch_result is changed
