---
- hosts: all
  tasks:
       - name: Enable firewall for Domain, Public and Private profiles
         community.windows.win_firewall:
             state: enabled
         profiles:
            - Domain
            - Private
            - Public
         tags: enable_firewall
         
