---
- hosts: all
  tasks:
    - name: task1
      command: "whoami"
      register: user_name

    - name: task2
      command: "pwd"
      register: user_home

    - name: printing 1
      debug:
        msg: "{{ user_name }}"

    - name: printing 2
      debug: 
        msg: "{{ user_home }}"
