---
- hosts: all
  vars:
    username: prabhanjan
    pwd_path: redhat
  tasks:
    - name: task1
      ansible.builtin.user:
              name: "{{ username }}"
              password: "{{ lookup('ansible.builtin.password', '{{ pwd_path }}', length=16, encrypt='sha512_crypt') }}"
    - name: task2
      command: whoami
