---
- name: Listen for events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
     - name: Say Hello
       condition: event.payload.message == "Ansible is cool"
       action:
         run_playbook:
           name: hello.yml
