---
- name: Create AAP Project, Job Template, and Schedule
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create Schedule for Job Template
      ansible.controller.schedule:
        controller_host: https://192.168.122.14
        controller_username: admin
        controller_password: redhat
        validate_certs: false
        name: demo_project_schedule
        unified_job_template: 7
        rrule: "DTSTART;TZID=UTC:20250413T030000 RRULE:FREQ=DAILY;INTERVAL=1"
        state: present
