---
- name: Create SSH credential in AAP
  hosts: localhost
  gather_facts: false
  collections:
    - ansible.controller

  tasks:
    - name: Create SSH credential
      ansible.controller.credential:
        controller_host: "http://192.168.122.31"
        controller_username: "admin"
        controller_password: "redhat"
        validate_certs: false
        name: "My SSH Credential"
        description: "Created via playbook"
        organization: "Default"
        credential_type: "Machine"
        inputs:
          username: "ec2-user"
          password: "changeme"
        state: present


