- name: Create Galaxy Credential (fixed version)
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create Galaxy credential
      ansible.controller.credential:
        controller_host: https://192.168.122.31
        controller_username: admin
        controller_password: redhat
        validate_certs: false
        name: galaxy_cred
        description: "Galaxy access"
        credential_type: "Ansible Galaxy/Automation Hub API Token"
        organization: Default
        inputs:
          auth_url: https://galaxy.ansible.com
          token: dummy_token_abc

- name: Attach galaxy_cred to Default organization
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Set galaxy_cred as organization's default Galaxy credential
      ansible.controller.organization:
        controller_host: https://192.168.122.31
        controller_username: admin
        controller_password: redhat
        validate_certs: false
        name: Default
        galaxy_credentials:
          - galaxy_cred
          - Ansible Galaxy
          - Automation Hub Community Repository
          - Automation Hub Published Repository
          - Automation Hub RH Certified Repository
          - Automation Hub Validated Repository
