---
- name: Create Galaxy Credential (short version)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    controller: https://192.168.122.31
    user: admin
    pass: redhat
    org: Default

  tasks:
    - name: Create Galaxy credential
      ansible.controller.credential:
        controller_host: "{{ controller }}"
        controller_username: "{{ user }}"
        controller_password: "{{ pass }}"
        validate_certs: false
        name: galaxy_cred
        description: "Galaxy access"
        credential_type: "Ansible Galaxy/Automation Hub API Token"
        organization: "{{ org }}"
        inputs:
          auth_url: https://galaxy.ansible.com
          token: dummy_token_abc
