---
- name: Create Galaxy Credential (short version)
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create Galaxy credential
      ansible.controller.credential:
        controller_host: https://192.168.122.31
        controller_username: admin
        controller_password: redhat
        validate_certs: false
        name: galaxy_cred
        description: "Galaxy access"
        credential_type: "Ansible Galaxy/Automation Hub API Token"
        organization: default
