- hosts: all
  tasks:
    - name: Setting password
      ansible.builtin.set_fact:
        ansible_isam_username: "{{ credential.28.isam_username }}"
     
    - name: Setting password
      ansible.builtin.set_fact:
        ansible_isam_password: "{{ credential.28.isam_password  }}"
