---
- name: Create users with wait period
  hosts: all
  become: true
  tasks:
    - name: Create user rohan
      ansible.builtin.user:
        name: rohan
        state: present

    - name: Wait for 60 seconds
      ansible.builtin.pause:
        seconds: 60

    - name: Create user mandar
      ansible.builtin.user:
        name: mandar
        state: present


