---
- name: Touch-and-Sleep
  hosts: all
  gather_facts: false
  serial: 1

  tasks:
    - name: Touch /tmp/touch-and-sleep
      file:
        path: /tmp/touch-and-sleep
        state: touch

    - name: Sleep for sleepTime seconds
      pause:
        seconds: 60

